import { DocumentType, Identity } from "./commonModels";

export interface GenerateDocumentResponse {
  taskId: number;
  documentType: DocumentType;
}

export interface DocumentGenerationTaskStatus {
  id: number;
  caseId: number;
  formName: string;
  status: string;
  presignedUrl: string;
  createdAt: number;
  updatedAt: number;
}

export interface GetDocumentsAdditionalParams {
  type?: DocumentType;
  identity?: Identity;
  autoGenerated?: boolean;
  generationType?: string;
}

export interface ParseMarriageCertificateResponse {
  licenseHolder: string;
  registrationDate: string;
  licenseNumber: string;

  holderName: string;
  gender: string;
  nationality: string;
  birthDate: string;
  idNumber: string;

  spouseName: string;
  spouseGender: string;
  spouseNationality: string;
  spouseBirthDate: string;
  spouseIdNumber: string;
  seal: string;
}
